name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: bun install

      - name: Build create-effex-app
        run: cd packages/create-effex-app && bun run build

      - name: Check if version exists on npm
        id: check-version
        run: |
          cd packages/create-effex-app
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if npm view create-effex-app@$PACKAGE_VERSION version 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Version $PACKAGE_VERSION already exists on npm"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Version $PACKAGE_VERSION does not exist, will publish"
          fi

      - name: Publish to npm
        if: steps.check-version.outputs.exists == 'false'
        run: cd packages/create-effex-app && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Skip publish
        if: steps.check-version.outputs.exists == 'true'
        run: echo "Skipping publish - version already exists on npm"
